name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'BackEnd/**'
      - 'ecs/backend-task-def.json'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          cd BackEnd
          docker build -t ${{ secrets.BACKEND_ECR_URI }} .
          docker tag ${{ secrets.BACKEND_ECR_URI }}:latest ${{ secrets.BACKEND_ECR_URI }}:latest
          docker push ${{ secrets.BACKEND_ECR_URI }}:latest

      - name: Replace image URI in task definition
        run: |
          sed -i 's|__BACKEND_ECR_URI__|${{ secrets.BACKEND_ECR_URI }}|g' ecs/backend-task-def.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v3
        with:
          task-definition: ecs/backend-task-def.json
          service: final-backend-service
          cluster: final-project-cluster
          wait-for-service-stability: true
          wait-for-minutes: 10
      
      - name: Describe ECS service
        run: |
          aws ecs describe-services --cluster final-project-cluster --services final-backend-service --region us-east-2
          echo "Deployment completed successfully."