name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'BackEnd/**'
      - 'ecs/backend-task-def.json'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.BACKEND_ECR_URI }} ./BackEnd
          docker tag ${{ secrets.BACKEND_ECR_URI }}:latest ${{ secrets.BACKEND_ECR_URI }}:latest
          docker push ${{ secrets.BACKEND_ECR_URI }}:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/backend-task-def.json
          service: backend-service
          cluster: final-project-cluster
          wait-for-service-stability: true